### ISSUE TITLE
Position of Clock

### ISSUE THREAD

**Issue by vonlocklearj** [TheLumbee/qt-digital-clock#1]
The first thing we need to discuss is if we want the clock to be inside the main window or outside the main window. Do we even need the main window?

**Comment by TheLumbee** [comment]
If it's outside the main window, we'd have a blank main window just chilling, and then a clock somewhere else. Why do we need both?

**Comment by Chavan4** [comment]
Let's put inside the main window to make it simple.

**Comment by vonlocklearj** [comment]
I agree with Chavan4, lets put the clock inside the main window.

**Comment by TheLumbee** [comment]
Main window is not needed.
